### ISSUE TITLE
Kango Extension (IE 10) stops functioning after visiting some websites

### ISSUE THREAD

**Issue by matthill** [KangoExtensions/kango#85]
Running Windows 2008 R2 Standard, IE10

After installing the plugin and logging into and out of gmail, the plugin stops functioning.  It no longer executes the content scripts.

I have uploaded an example here:
https://github.com/matthill/kango-samples

After compiling and installing the IE extension on IE 10 running Windows 2008 R2 Standard, do the following:
1. Visit http://www.google.com.  Notice the plugin icon flashes green for 2 seconds (it will do this anytime a page finishes loading)
2. Visit http://www.gmail.com
3. Login to gmail
4. Logout of gmail
5. Go to www.google.com (Notice the plugin no longer flashes green).

Any page you now access will no longer execute the plugin, notice that the plugin will never flash green again.  The only way to resolve this is to close Internet Explorer and open it back up again.

**Comment by akrylysov** [comment]
Unfortunately we can't reproduce the issue. Could you please send us the compiled extension and the list of installed IE add-ons?

**Comment by matthill** [comment]
There are no other plugins installed.  I have setup an instance where this problem is 100% reproducible.  All I did was install Windows 2008 R2 and then install this simple plugin.  Can I send the login information to extensions@kangoextensions.com, or is there another e-mail for you?

**Comment by akrylysov** [comment]
Fixed.

**Comment by crandall-chow-sp** [comment]
What was the fix?  Anything you can share?  We see our BX on IE hang on occasion,and sometimes bouncing IE doesn't fix it.  We end up having to kill the KangoEngine.exe process.
